### ISSUE TITLE
Prebid currency file stopped updating after 31st March 2021

### ISSUE THREAD

**Issue by kanchika-automatad** [prebid/currency-file-generator#20]
Looks like the prebid currency file isn't updated since 31st march 2021. (https://cdn.jsdelivr.net/gh/prebid/currency-file@1/latest.json) 
Please let us know if we need to use a different file.

**Comment by mkendall07** [comment]
thanks for opening. We have a ticket for the issue here https://github.com/prebid/Prebid.js/issues/6524
Should be resolved shortly.
